#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "ServoSystemDemo"
#define PROJECT_VERSION "0.1.0"
/* #undef PROJECT_VERSION_MAJOR */
#define PROJECT_VERSION_MINOR "1"
/* #undef PROJECT_VERSION_PATCH */
#define VERSION_BUILD_TIME "0.1.0_20251119_15.19.36"

#endif //_VERSION_H
