#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "ServoSystemDemo"
#define PROJECT_VERSION "0.0.1"
/* #undef PROJECT_VERSION_MAJOR */
/* #undef PROJECT_VERSION_MINOR */
#define PROJECT_VERSION_PATCH "1"
#define VERSION_BUILD_TIME "0.0.1_20241227_16.23.31"

#endif //_VERSION_H
