#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "ServoSystemDemo"
#define PROJECT_VERSION "0.2.0"
/* #undef PROJECT_VERSION_MAJOR */
#define PROJECT_VERSION_MINOR "2"
/* #undef PROJECT_VERSION_PATCH */
#define VERSION_BUILD_TIME "0.2.0_20251224_14.20.33"

#endif //_VERSION_H
